### ISSUE TITLE
404 | This page could not be found.

### ISSUE THREAD

**Issue by Starboy-Sharma** [richiemcilroy/drag#1]
I had completed the signup process. After that the web is asking for paste the project URL. I pasted my portfolio URL which is https://pankaj-sharma-portfolio.netlify.app/. After complete the process it shows me 404. Please also check the screen shot
![Screenshot from 2021-08-10 20-40-05](https://user-images.githubusercontent.com/31812684/128892273-552bee7f-5dd2-4412-9582-8a4a210057f3.png)

**Comment by richiemcilroy** [comment]
Hey thanks for opening this issue - I tried to reply earlier but there was a problem with GitHub.

Basically, I haven't added in any URL filtering yet to the project creator part. So if you just put pankaj-sharma-portfolio.netlify.app without https or www, it should work :)
